kind: Route
apiVersion: route.openshift.io/v1
spec:
  host: ${project.artifactId}.${domain}
  to:
    kind: Service
    name: ${project.artifactId}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
